name: Docker build

on:
  release:
    types: [created]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/qtmsheep/qtmsheep.com:latest
            ${{ secrets.DOCKER_REGISTRY }}/qtmsheep/qtmsheep.com:${{ steps.tag_name.outputs.TAG_NAME }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update the service via webhooks
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.QTMSHEEP_COM_SERVICE_WEBHOOK }}
          method: POST
